name: release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -v -o garminDataSummary

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: garminDataSummary
          path: ./garminDataSummary

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: garminDataSummary

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./garminDataSummary