name: release
on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
            filename: garminDataSummary_amd64_linux
          - goarch: arm
            goos: linux
            filename: garminDataSummary_arm_linux
          - goarch: amd64
            goos: darwin
            filename: garminDataSummary_amd64_macOS
          - goarch: arm64
            goos: darwin
            filename: garminDataSummary_arm64_macOS
          - goarch: amd64
            goos: windows
            filename: garminDataSummary_amd64_windows.exe
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-s -w" -trimpath -gcflags '-B -l' -v -o ./${{ matrix.filename }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.filename }}
          path: ./${{ matrix.filename }}

  release:
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/garminDataSummary*